### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by kevinspacey** [bvaughn/angular-form-for#100]
Hello @bvaughn , i think add changelog to project is good idea.

**Comment by bvaughn** [comment]
Hey @kevinspacey,

The [release log](https://github.com/bvaughn/angular-form-for/releases) always existed, but I've added an explicit [changelog](https://github.com/bvaughn/angular-form-for/blob/master/CHANGELOG.md) at your request as well.

**Comment by kevinspacey** [comment]
thanks!
