### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by wlingke** [bvaughn/angular-form-for#105]
Please correct me if I'm wrong - on line 473 in form-for.css it shows:
```
.form-for-tooltip-icon:hover {
  background-color: tooltip-icon-background-color-hover;
}
```

This looks like it should've been a color?

**Comment by bvaughn** [comment]
Nope, you're right. The hover-state should refer to a darker color. Looks like one of my Stylus variables got mixed up. I'll address this with the next release.
