### ISSUE TITLE
Material templates do not work properly without jQuery

### ISSUE THREAD

**Issue by wlingke** [bvaughn/angular-form-for#106]
I am having a bunch of trouble getting 3.0.4 working. It loads fine but the behavior isn't what I expect. For instance, when you click on a text-input, the label should move up and the placeholder should appear. This doesn't happen for me. Or when I click on a select, it scrolls me to the top of the page. When I type text into inputs, they disappear but when I click on the inputs, they come back

I am using angular-material 0.8.3 and angular 1.3.15, 

I made an example here: http://jsfiddle.net/Ly22uhbv/4/

**Comment by bvaughn** [comment]
Ah..the problem is that you're using Angular Material 0.8.3, a version that has quite a few bugs. :)

This is why my own docs page points to head. Have you tried v0.9.0-rc2? That's likely got fixes for the issues you've mentioned.

**Comment by wlingke** [comment]
I've swapped them out for head as you suggested and the problems persist.

http://jsfiddle.net/Ly22uhbv/5/

**Comment by wlingke** [comment]
I discovered that including Jquery makes the form work: http://jsfiddle.net/Ly22uhbv/7/

Seems like there's still an issue with jquery

**Comment by bvaughn** [comment]
Hmm. Very interesting. It looks like Angular Material does not require jQuery as of [issue 60](https://github.com/angular/material/issues/60). Also looks like [the Angular Material demo page](https://material.angularjs.org/#/demo/material.components.input) isn't requiring it...

I'm not sure what in my library would be requiring jQuery, or why it would fail silently like this... hmm.

**Comment by bvaughn** [comment]
@wlingke, I'm very sorry that you've run into this issue. Realistically, I probably won't be able to fix it soon. I moved this weekend and my evenings are currently filled with unpacking. I just spent about 45 minutes debugging but I haven't found the root cause.

If you find anything, please feel free to add notes (or post a PR!) else I'll get back to it when I can.

**Comment by bvaughn** [comment]
Hi again @wlingke!

I'm so sorry it took me a couple of weeks to gat around to this. I've been very busy after moving. I'm happy to report that the most recent release of formFor- [version 3.0.5](https://github.com/bvaughn/angular-form-for/releases/tag/3.0.5)- resolves the issue you've reported.

Here's an updated Plunker: http://jsfiddle.net/bvaughn/tmj6zzLz/

**Comment by wlingke** [comment]
Awesome!



—
