### ISSUE TITLE
Select lists don't seem to update the scope model whenever the value changes

### ISSUE THREAD

**Issue by donmasakayan** [bvaughn/angular-form-for#108]
Check out this plunker: http://plnkr.co/edit/vamTf1rrq5AZxMzsw2Mv
Go ahead and fill up the form. You'll notice that the text fields seem to update `$scope.formData` just fine whenever their values change.

However the select list doesn't seem to work in that regard.

Digging through the source files, I notice that we set a `$watch` for changes to `$scope.model.binding`. However, it seems as if `$scope.model.binding` or even `$scope.model` doesn't register any changes despite changing the select list's value.

**Comment by donmasakayan** [comment]
I noticed that this started happening after you broke down the select-list template into partials with `ng-include`... Which makes me think it might be related to this issue:

http://stackoverflow.com/questions/19408883/angularjs-select-not-2-way-binding-to-model

**Comment by bvaughn** [comment]
Hey @donmasakayan. Thanks for reporting this bug.

That issue (an isolate scope masking and overriding a parent value) happens if you don't use nested properties. formFor's directives always bind to `model.bindable` so isolate scopes should not interfere.

That being said, I see what you're reporting and I'm not initially sure why it's happening. I'll take a look.

**Comment by bvaughn** [comment]
Interesting. This problem goes away if jQuery is included. (See my fork: http://plnkr.co/edit/d4iYWRyXP8zla2GyxsRF)

**Comment by bvaughn** [comment]
Sure enough though, you are correct in your suggestion that the `ng-include` seems to be causing the problem. Or rather that, if I remove it, the problem goes away. Very interesting!

**Comment by bvaughn** [comment]
I'll push out an update shortly with this issue fixed. Thanks again for the clean bug report and the plunker!

**Comment by donmasakayan** [comment]
Thanks for fixing this issue quickly! :+1:

**Comment by bvaughn** [comment]
No problem!

Check out [version 3.0.5](https://github.com/bvaughn/angular-form-for/releases/tag/3.0.5). It's got the fix!
