### ISSUE TITLE
How to change  the text of the submit button when using formforBuilder?

### ISSUE THREAD

**Issue by na57** [bvaughn/angular-form-for#109]
Hi, everyone.
When I use formforBuilder to generate my form(just like the demo: http://bvaughn.github.io/angular-form-for/#/demo/form-builder-markup ), I want to change the text of the submit button ( "submit" is defult). How should I do that?

**Comment by bvaughn** [comment]
Check out the [submitButton docs](http://bvaughn.github.io/angular-form-for/#/documentation/submitButton). They show some examples of this. In short, just specify a `label` like so:

```html
<submit-button label="Save"></submit-button>
```
