### ISSUE TITLE
Blank value treated as null instead of undefined

### ISSUE THREAD

**Issue by palodelincak** [bvaughn/angular-form-for#110]
Hey there,

I understand that this issue is not fully tied with your plugin, but please consider it as a question, or maybe improvement if you'll find it as benefical.

I'm using `select-field` directive with `allow-blank` option - this works fine. But you use `undefined` value for blank option and this is causing issues.

*Example:*
I have object `person.age`, once this attributes is changed to blank option, attribute is set to `undefined` and is not sent to my backend API. This will cause that this attribute is not changed in backend because is not present. What I need to set this attribute to `null` instead of `undefined`.

Is it possible to use `null` instead of `undefined` for blank options?

**Comment by bvaughn** [comment]
Could you not use an empty string instead?

**Comment by palodelincak** [comment]
Yes, empty string will do the trick. This is in my directive:
```
$scope.emptyOption = {};
$scope.emptyOption[$scope.labelAttribute] = '';
$scope.emptyOption[$scope.valueAttribute] = '';
$scope.placeholderOption = {};
$scope.placeholderOption[$scope.labelAttribute] = $scope.placeholder;
$scope.placeholderOption[$scope.valueAttribute] = '';
```

But, I found some other issues related with combination of allow-blank and placeholder for selects... Take a look at this Plunker - http://plnkr.co/edit/kTC6g03jPZxM3AD3Ctyx?p=preview. I think number 5) should be treated exactly the same as number 2). But as you can see there is a difference between `undefined` and `null`.

So as I said I can use empty string and my backend will treat it as null - this is fine and works. But my backend will return `null` instead of empty string and as you can see number 5) is the problem. Do you consider this as a bug/enhancement or is this your desired behaviour?

**Comment by palodelincak** [comment]
Also, I've updated Plunker because I found another issue. As you can see number 6 - it has preselected value 4, but options are not present in moment of render - they are loaded after directive is rendered. Once options are present, value is preselected correctly, but placeholder is present instead of blank option. Number 6 should work exactly like number 4.

**Comment by bvaughn** [comment]
Hm. I'll need to give that some thought, something I can't do at the moment because I'm at work.

Thanks for your patience! I'll try to give it some thought as soon as I can. :)

**Comment by bvaughn** [comment]
Just a heads-up. My laptop battery died and I had to take it in for a repair. It will likely be about a week before I get it back and so I'm not going to be able to address this issue as quickly as I'd normally like to. I hope this isn't too much of an inconvenience. I'll get to it as soon as I'm able! Thanks for understanding. :)

**Comment by palodelincak** [comment]
No problem and thanks for getting back to me! Take care of your things... :-)

**Comment by bvaughn** [comment]
Got my laptop back this evening. Spent a bit of time looking at this and I'm still not sure of an elegant solution. I'll try to spend some more time on it tomorrow or Friday. Sorry for the delay!

PS Your plunk is great. Thanks for that.

**Comment by bvaughn** [comment]
I believe I've found a working solution for this.

The issue here is that [Angular's `select` directive](https://docs.angularjs.org/api/ng/directive/select) is auto-generating an empty `<option>` tag when the `ng-model` value doesn't exist within `ng-options`. This is the correct behavior for because it avoids forcing an arbitrary selection that the user didn't intend.

Form for is doing a lot of meta stuff on top of `select` but in the end I'm still handing it a set of options and a default selection, and the "empty" options need to match. So what I've done is compare the model's selected value to null, undefined, or empty string and if either of those match, set the value of the placeholder field to be the same.

**Comment by bvaughn** [comment]
Thank you for your patience. Release [3.0.7](https://github.com/bvaughn/angular-form-for/releases/tag/3.0.7) should have this fix for you. :)

**Comment by palodelincak** [comment]
Thank you very much! I'll test it as soon as possible :-)

**Comment by palodelincak** [comment]
Thanks for you fixes again. I just tested it and found another issue.

Take a look at this Plunk:
http://plnkr.co/edit/pTZU4JY8YUbqPbTQFa4s?p=preview

When there is select with options which are loaded after directive is rendered, allow-blank is enabled and value is preselected then placeholder value is present instead of blank option.

1) When I select some other value, placeholder is replaced with blank option.
2) When I select placeholder option, blank option is added to list of options - so it looks like [blank], [placeholder], value, value...

As you can see this is an issue only for remote (delayed) options load. When options are present in moment of render it works as expected.

**Comment by palodelincak** [comment]
Hello Brian, I know you're probably busy, but can you reopen this bug so we don't loose track of this? Thanks!

**Comment by bvaughn** [comment]
Hi Palo. I thought you had filed the newly discovered issue as #115. My apologies.

Please file the placeholder as a separate issue if you would. :)
