### ISSUE TITLE
"placeholder" View Rule not working in FormBuilder

### ISSUE THREAD

**Issue by jimnorth55** [bvaughn/angular-form-for#111]
I'm using the following view/validation rule object in a form with the 'form-for-builder' attribute set.  The form element is being generated as expected, with the exception of the placeholder.  See attached screen shot.

           email: {
                inputType: 'text',
                label: 'Email Address',
                required: true,
                type: 'email',
                placeholder: 'Enter your email address',
                help: 'The email address we should use when responding.'
            },

![capture](https://cloud.githubusercontent.com/assets/5594002/7671591/2c108baa-fca5-11e4-9f79-cc64fa30c31d.gif)

**Comment by bvaughn** [comment]
Just a heads-up. My laptop battery died and I had to take it in for a repair. It will likely be about a week before I get it back and so I'm not going to be able to address this issue as quickly as I'd normally like to. I hope this isn't too much of an inconvenience. I'll get to it as soon as I'm able! Thanks for understanding. :)

**Comment by jimnorth55** [comment]
Brian,

Certainly there is no rush on my account.  I appreciate your contribution
of what I think is an excellent module to the Angular community.  And,
thank you for your attention to the issue.

Cheers!
Jim

**Comment by bvaughn** [comment]
Thank you for the kind words and for your patience. :)

Got my laptop back after work this evening. Just fixed the issue and I will create a release soon, once I've had a chance to look into #110.

**Comment by bvaughn** [comment]
Release [3.0.6](https://github.com/bvaughn/angular-form-for/releases/tag/3.0.6) is out for you.

**Comment by jimnorth55** [comment]
Thank you!
