### ISSUE TITLE
Controller 'ngModel', required by directive 'ngChange', can't be found!

### ISSUE THREAD

**Issue by sona1393g** [bvaughn/angular-form-for#112]
how one can use ng-change with select-field while using getting this error..

**Comment by bvaughn** [comment]
Hi @sona1393g.

Form for isn't really intended to be used with built-in directives like `ngChange`. IMO they're not really necessary. Why not just use `$scope.$watch`?

So if you have a select-field declared in your view like this:
```html
<select-field label="Example select menu"
              attribute="ctrl.formData.selectableField"
              options="ctrl.selectableOptions">
</select-field>
```
You could watch for changes in your controller like this:
```js
$scope.$watch('ctrl.formData.selectableField',
  function(newValue, oldValue) {
    // Do whatever you want here
  });
```
