### ISSUE TITLE
Not selected value, not allowed blank - ng-model is not updated

### ISSUE THREAD

**Issue by palodelincak** [bvaughn/angular-form-for#115]
Hello, so I had finally some time to test your fixes you did to resolve #110 and I found one issue.

Tak a look at this Plunk:
http://plnkr.co/edit/WnShJud8kAl0hTVjrPWA?p=preview

When select doesn't have selected value and allow-blank is false, ng-model should reflect displayed value from select (first from options). But it does not. Model gets updated when I select some value from select.

This is not issue for version 3.0.6, but introduced in 3.0.7.

**Comment by bvaughn** [comment]
Thanks for the info. I'll look into it when I can :)

**Comment by bvaughn** [comment]
I haven't forgotten about this issue. I've just been *really* slammed at work. (Ditto for #125.)

I think the next formFor release (hopefully soon) will have some heavy refactoring in this component. It's just gotten too complex. I'm going to probably split the current `<select-field>` into two separate components- `<select-field>` and `<type-ahead>`. I think this will simplify the directive and the templates significantly.

**Comment by palodelincak** [comment]
Yes, this split will be a good decision!

**Comment by bvaughn** [comment]
Made decent progress this weekend on the refactor (see the [`select-field-refactor` branch](https://github.com/bvaughn/angular-form-for/tree/select-field-refactor)) but haven't ironed out all of the Angular Material issues, unfortunately. It's just different enough to be a hassle...

**Comment by bvaughn** [comment]
Resolved by [Pull #127](https://github.com/bvaughn/angular-form-for/pull/127)
