### ISSUE TITLE
Add name property to input tags in templates to enable testing models

### ISSUE THREAD

**Issue by hutzelknecht** [bvaughn/angular-form-for#116]
I have been trying to figure out how to test if entering a value changes the model data. The problem is that i can't set the viewValue in my testing framework the way angular suggests (see: http://stackoverflow.com/questions/15219717/to-test-a-custom-validation-angular-directive)

    describe('integer', function() {
        it('should pass with integer', function() {
          form.somenum.$setViewValue('3'); // this doesn't work without name attributes !
          $scope.$digest();
          expect($scope.model.somenum).toEqual('3'); // this doesn't work either !
          expect(form.somenum.$valid).toBe(true); // this doesn't work either !
        });
    });

In order to make this testing possible, we would have to add a name attribute to input fields in all the templates.

    <input  aria-manager

        id="{{ model.uid }}"
        name="{{ attribute }}" // like here !
        class="form-control"
    ...

**Comment by bvaughn** [comment]
Hi @hutzelknecht.

I understand your request. My schedule's kind of busy at the moment but I'll try to get this committed sometime over the next few days. :)

**Comment by bvaughn** [comment]
Sorry for the delay. I'll get this out with the next release. Hoping to address a filtered-select issue before releasing.
