### ISSUE TITLE
Select placeholder is not working properly for remote loaded options

### ISSUE THREAD

**Issue by palodelincak** [bvaughn/angular-form-for#125]
I wrote this comment for issue #110.

Take a look at this Plunk:
http://plnkr.co/edit/pTZU4JY8YUbqPbTQFa4s?p=preview

When there is select with options which are loaded after directive is rendered, allow-blank is enabled and value is preselected then placeholder value is present instead of blank option.

1) When I select some other value, placeholder is replaced with blank option.
2) When I select placeholder option, blank option is added to list of options - so it looks like [blank], [placeholder], value, value...

As you can see this is an issue only for remote (delayed) options load. When options are present in moment of render it works as expected.

**Comment by bvaughn** [comment]
Resolved by [Pull #127](https://github.com/bvaughn/angular-form-for/pull/127)

**Comment by bvaughn** [comment]
@palodelincak I've just created release 4.0.0 which should *hopefully* address the various select issues you've reported. I'd like to apologize for taking longer than usual to fix these issues. Work (my day job) has been very busy.

I'd also like to thank you for the excellent example Plunkers you included with these default reports. They were very helpful. They're probably the best bug reports I've gotten here. :)

**Comment by palodelincak** [comment]
@bvaughn You're welcome! It's better to see once than hear a hundred times :-). And thank you very much for your hard work on this beautiful plugin! I'm going to take a look at your changes and test it.
