### ISSUE TITLE
Add support for trimming input values

### ISSUE THREAD

**Issue by flowerrrr** [bvaughn/angular-form-for#126]
Angular offers support for trimming form input values automatically. 
Would be great to have that feature in formFor as well.

**Comment by bvaughn** [comment]
Hi @flowerrrr!

That sounds like a reasonable request. I'm currently working on release 4.0 (focused on select and type-ahead fields) but I'll try to squeeze this in before the release goes out in a couple of days (hopefully).

**Comment by bvaughn** [comment]
Release [4.0.1](https://github.com/bvaughn/angular-form-for/releases/tag/4.0.1) is out with this feature.

You can demo it here:
http://bvaughn.github.io/angular-form-for/#/demo/form-metadata

The key to using it is `FormForConfiguration.enableAutoTrimValues(); `
