### ISSUE TITLE
Error focused and blured

### ISSUE THREAD

**Issue by lobor** [bvaughn/angular-form-for#130]
I have this error $scope.focused is not a function and $scope.blurred is not a function
with this code

```html
<form form-for="sci" form-for-builder validation-rules="validationAndViewRules">
</form>
```

```javascript
$scope.sci = {};
$scope.validationAndViewRules = {
    email: {
        required: true,
         type: 'email',
        inputType: 'text',
         label: 'Email'
    }
};
```

**Comment by bvaughn** [comment]
Hi @lobor,

Where are you seeing the error? Which version of formFor?

I don't see any error like this on the formFor docs site (using the newest 4.0 release) ~ http://bvaughn.github.io/angular-form-for/#/demo/form-builder-markup

**Comment by lobor** [comment]
I use angular 1.4.1

**Comment by bvaughn** [comment]
But where are you seeing this error? (Can you post a Plunker with an example?)

I've also tested with Angular 1.3.6 and 1.4.1 before releasing version 4.0 and didn't see the error

**Comment by bvaughn** [comment]
Going to close this since I'm unable to reproduce it given the info you've provided (and I haven't heard back from you with more). Please link me to a Plunker that shows the error you're seeing if you're still having problems and I'll be happy to take a look!
