### ISSUE TITLE
Angular 1.4.1 compatibility with $attributes service

### ISSUE THREAD

**Issue by hutzelknecht** [bvaughn/angular-form-for#132]
Hi Brian,

thanks for all the busy work you put into form-for the last few weeks. I just migrated to Angular 1.4.1 and noticed that in directives, the $attributes service now actually has all the attributes as properties with a value of undefined. This makes the following lines break:

    $scope.onFocus = function () {
        if ($attributes.hasOwnProperty('focused')) {
            $scope.focused();
        }
    };

so the output of the generated form-for code would have to check not only with "hasOwnProperty", but also for a truthy value or the existance of a function before calling it:

    $scope.onFocus = function () {
        if (typeof $attributes['focused'] === 'function') {
            $scope.focused();
        }
    };

No idea how to accomplish this in typescript. but this is really the only issue i found so far with compatibility with angular 1.4.1

**Comment by bvaughn** [comment]
Hi @hutzelknecht,

You're welcome. And thank you. :)

I'll try to take a look at this this evening. Off the top of my head, I don't know what may have changed between versions that would have caused this. (What version did you upgrade from?)

**Comment by hutzelknecht** [comment]
I switched from 1.3.15 to 1.4.1. There was no mention of this change on the migration guide. Haven't figured out why it happens so far.

**Comment by bvaughn** [comment]
This fix is out in the 4.0.3 release.
