### ISSUE TITLE
submitButton class [buttonClass]

### ISSUE THREAD

**Issue by lobor** [bvaughn/angular-form-for#133]
Hi an error exists with buttonClass
When in your code display $attributes on line 1792 exists buttonclass and not buttonClass.

i change it and add
```javascript
$scope.buttonClass = $attributes.buttonclass;
$element.find('button').addClass($scope.buttonClass);
```

**Comment by bvaughn** [comment]
This isn't an error. The [submitButton docs](http://bvaughn.github.io/angular-form-for/#/documentation/submitButton) show that the expected attribute name is `buttonClass`.

JavaScript is a case-sensitive language. This means that variables (and other things) must always be typed with the correct capitalization of letters. For example:

```js
var hash = {};
hash['buttonclass'] = 'This is lower case';
hash['buttonClass'] = 'This is mixed case';
```

That will create a hash with 2 keys:
```
Object {buttonclass: "This is lower case", buttonClass: "This is mixed case"}
```

Angular converts the HTML attribute format (e.g. `my-attribute`) to a camel case format (e.g. `myAttribute`) automatically . If you want to pass a custom button class you can do it like this:

```html
<submit-button label="Disabled button" button-class="something"></submit-button>
```

**Comment by bvaughn** [comment]
I'm closing this because I'm fairly sure it's just a misunderstanding. Please let me know if not and I'll take another look. :)
