### ISSUE TITLE
Object.defineProperty (used in FormForConfiguration) causes an error for IE8

### ISSUE THREAD

**Issue by vipinmathew2013** [bvaughn/angular-form-for#134]
please give me an example of using formfor in template of custom directive

i am getting the following error
https://docs.angularjs.org/error/$compile/ctreq?p0=formFor&p1=textField

**Comment by bvaughn** [comment]
That error is just indicating that the textField directive you're using requires a parent formFor directive in order to function.

If you want more specific advice, please link me to a Plunker demonstrating what you're doing and the error you're encountering.

**Comment by vipinmathew2013** [comment]
Thanks for the quick reply the problem was due to some cached script which triggered it,

**Comment by vipinmathew2013** [comment]
hi,i am getting error in line63 when i try in IE8,i have included the es5.js as well.
below line in form-for.js gives error

Object.defineProperty(FormForConfiguration.prototype, "autoGenerateLabels", {

Please help
Thanks

**Comment by vipinmathew2013** [comment]
![image](https://cloud.githubusercontent.com/assets/11713640/8500003/e7697e2a-215d-11e5-8401-6b23bc3a891e.png)

**Comment by bvaughn** [comment]
Hmm. That's unfortunate.

formFor hasn't supported IE8 for some time now, although I also try to make it so that IE8 can be used if effort is made to polyfill things. Looks like there isn't really a great way to polyfill `Object.defineProperty` though.

If IE8 support is important to you, I can remove `Object.defineProperty` in favor of publicly written attributes in the next release. Will you confirm that this is the only IE8 compatibility problem for you first though?

**Comment by bvaughn** [comment]
@vipinmathew2013 I've removed the `Object.defineProperty` references in `FormForConfiguration`. I have not made a release with this change in it yet. If you'd be interested in trying it out- just point your browser to HEAD like so: http://rawgit.com/bvaughn/angular-form-for/master/dist/form-for.js

Let me know if this resolves your IE8 issue and I can make a 4.0.5 release.

**Comment by vipinmathew2013** [comment]
Hi @bvaughn, adding the above script src resolved that issue.
but currently i am facing below issue
1)-&lt;form class="form-group" form-for="formData" validation-rules="validationAndViewRules" submit-with="ctrl.submit()"&gt; ..this is not getting rendered  whereas
&lt;div text-field attribute="name"  label="Enter name" &gt;  gets rendered but <b>validations are not working</b> also <b>scope is not binding with formData </b>

Thanks

**Comment by vipinmathew2013** [comment]
i can se these errors logged in IE8
![image](https://cloud.githubusercontent.com/assets/11713640/8593438/4e55bdf8-25fd-11e5-9779-696c3c3c269b.png)
