### ISSUE TITLE
Generated stuff...

### ISSUE THREAD

**Issue by lookfirst** [bvaughn/angular-form-for#135]
Seems kind of weird...

https://github.com/bvaughn/angular-form-for/blob/master/dist/form-for.js#L2795-L2840

**Comment by bvaughn** [comment]
Agreed. Seems like maybe a TypeScript compiler bug. Not sure if there's anything I can do about it.

Shouldn't affect anything though, other than adding a couple of bytes to the JS file size.

**Comment by bvaughn** [comment]
Is this causing you any trouble or were you mostly just pointing it out?

**Comment by lookfirst** [comment]
Just pointing it out. Looks like lots of empty function calls. Can't be very efficient and is probably easily removed with a regex in the build process.

**Comment by bvaughn** [comment]
Fair enough. I doubt there's much of a performance impact as those function bodies are empty and only invoked when the file is initially processed.

May be worth removing as a post-build step I suppose. I'll leave this ticket open for now. :)
