### ISSUE TITLE
[feature] x-editable

### ISSUE THREAD

**Issue by lookfirst** [bvaughn/angular-form-for#136]
What do you think of adding support for x-editable type input fields?

**Comment by bvaughn** [comment]
Seems like it could be an interesting project but I'm not sure I have the bandwidth to take it on right now. You're the first person to request it (though I assume you wouldn't be the only one to make use of it).

Would you be interested in contributing toward this feature?

**Comment by lookfirst** [comment]
Might be a good reason to learn typescript. That's my major barrier right now.

**Comment by bvaughn** [comment]
I can't say enough nice things about it. :)

I work at Google so I use the [Closure compiler](https://developers.google.com/closure/compiler/docs/js-for-compiler) a lot during my day job. I've also used CoffeeScript a fair amount in the past. TypeScript is much more enjoyable than either.

If you do decide to give it a try, I recommend checking out the 30-day demo for [WebStorm](https://www.jetbrains.com/webstorm/) too. It's fantastic.

**Comment by vipinmathew2013** [comment]
hi,i am getting error in line63 when i try in IE8,i have included the es5.js as well.
below line in form-for.js gives error

Object.defineProperty(FormForConfiguration.prototype, "autoGenerateLabels", {

Please help
Thanks

**Comment by lookfirst** [comment]
I was a fan of coffeescript until babel and es6. Haven't had time to work with typescript... Still not convinced all the tooling is there yet and I feel like there is a small barrier to entry for contributions still. I suspect though that in a year or two we will all be writing it.

Already a open source license user of idea under my Apache committer membership. Love it!

What I'm really looking for is something very much like your project but with just bootstrap support. I don't want special elements for declaring forms. Just standard html. I see why you went that route but I'd rather not put barriers to entry up for people by making them learn new elements. Just annotate basic form elements with angular and bootstrap specific markup.

Sorry, getting off topic now. If you'd like to close this issue no worries. Thanks for your fast response and helpful attitude!

**Comment by bvaughn** [comment]
I think the tooling is sufficient to make it a very compelling choice. Far superior to vanilla JS and far more elegant and compact (subjectively) than Closure.

Hm. Interesting concept. formFor could be refactored to allow for decorating regular input elements while also offering the more full-featured, label-and-field combo directives... but I don't know if it would be worth the effort.

You may also be interested in a side project of mine that's kind of fizzled out at the moment - [Forms JS](https://github.com/forms-js/forms-js). If you have any interest in joining, I haven't given up on it yet. The other contributors didn't really have the time though and I'm not sure I want to tackle another library solo.

I'm going to close this for now but...it's a nice though, and if other people see it and like the idea, maybe I'll consider it. :)
