### ISSUE TITLE
Bind click event for the icon in textfield

### ISSUE THREAD

**Issue by vipinmathew2013** [bvaughn/angular-form-for#138]
help me bind the click event for textfield icon

http://plnkr.co/edit/AUAwMawurYzzNrxz2qFl?p=preview

**Comment by bvaughn** [comment]
Previously, only the Bootstrap templates supported these events. I just pushed a minor change (in version 4.0.4) that adds this feature to the default formFor templates as well.

Your Plunker also has a small error:
```js
$scope.fnicondate-function(){alert('fired');}
```

Here's a forked, updated version of your Plunker that works:
http://plnkr.co/edit/zDHQM9JMn3s3eaq2Wy1b?p=preview

**Comment by vipinmathew2013** [comment]
do we have datepicker control  in FormFor ? i wanted a calender to popup on that icon click?

**Comment by bvaughn** [comment]
No. Date pickers are pretty complicated and kind of properly treated as their own thing.

You could hook a date picker into formFor (meaning that you could create a relatively small directive that wires a date picker of your choosing up with formFor's validation) following the **Creating a Custom Field** guide here: http://bvaughn.github.io/angular-form-for/#/demo/input-types

**Comment by vipinmathew2013** [comment]
http://plnkr.co/edit/iH8EZyzB2bBOrrBfhNFI?p=preview

can u please check the above plunker and tell me how i can update the formdata object {dob: value} as soon as i select the date.thanks

**Comment by bvaughn** [comment]
This question seems to be more about the datepicker component you're using than formFor. Given the way your code is structured, if your datepicker dispatches some sort of change event (likely) then you'd just need to set `this.formData.dob` in the change handler.
