### ISSUE TITLE
Type ahead: TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by nickguletskii** [bvaughn/angular-form-for#139]
TypeError: Cannot read property 'bind' of undefined
        at TypeAheadFieldDirective.link.setDelayedFilterTextFocus 

This happens because `$element.find('input')` in https://github.com/bvaughn/angular-form-for/blob/4.0.4/source/directives/type-ahead-field.ts#L248 returns an array of elements, not a single element.

**Comment by bvaughn** [comment]
Hi Nick,

Could you provide a Plunker that demonstrates this problem? (Or at least give me a little context of where you're seeing it?)

I'm not seeing it on the [docs site](http://bvaughn.github.io/angular-form-for/#/demo/type-ahead) or locally.

Also the jQuery/jQlite `find` method decorates the collection object it returns with methods like focus and passes through to the set, so it doesn't cause the problem you describe for me- even if I use a selector that matches multiple items.

**Comment by nickguletskii** [comment]
Hi, here's a plunk that demonstrates the issue.

http://plnkr.co/edit/799fCypXNVaoi5klgWBy?p=preview

This happens when you click on the type ahead.

**Comment by bvaughn** [comment]
Thank you for bringing this to my attention! And thanks for the helpful Plunker. :)

This issue has been fixed in release [4.0.5](https://github.com/bvaughn/angular-form-for/releases/tag/4.0.5).

**Comment by nickguletskii** [comment]
Thanks, works perfectly now. :)
