### ISSUE TITLE
How to define class for label

### ISSUE THREAD

**Issue by osimicek** [bvaughn/angular-form-for#144]
Hi, everyone.
Is there any way how to define class for label of a field? I need to add 'sr-only' (screen readers only) class to label element and don't know how.
Thanks

**Comment by bvaughn** [comment]
Hi @osimicek,

I think there are two options for this.

# Override the `form-for/templates/field-label.html` template

The [template overrides guide](http://bvaughn.github.io/angular-form-for/#/demo/template-overrides) gives examples of how to do this and it's pretty simple. You could fork [one of the existing label templates](https://github.com/bvaughn/angular-form-for/tree/master/templates/) and add your custom class.

This would be the fastest way to accomplish what you're looking to do.

# Add a configuration option to `FormForConfiguration`

Something similar was done for issue #131 and you can see the pull request [here](https://github.com/bvaughn/angular-form-for/pull/140).

**Comment by bvaughn** [comment]
Let me know your thoughts once you've had a chance to think it over. :)

**Comment by osimicek** [comment]
Thanks for reply.
I think the best solution is to add ng-class directive to a <label> element and add labelClass attribut to every form field type. labelClass attribute will contain prefered classes.
example:
<text-field ... labelClass=''sr-only'></text-field>
(inputClass and errorClass attributes can be added as well)

I hoped there was some easy way to do this.
At this moment I have really no extra time for implementing this. If I am the only one who find this useful, please close this issue.

**Comment by bvaughn** [comment]
Interesting. So you'd prefer having `labelClass` (and potentially `errorClass`) be configurable on a per-element basis vs having it be a global setting in `FormForConfiguration`? Out of curiosity, why?

Wouldn't it always be a global thing?

If you wanted to customize a specific directive's label, you could always do that with CSS child selectors.

**Comment by osimicek** [comment]
I think the FormForConfiguration isn't the correct way. It modifies all forms on web. I wanna setup only one form or only some fields.
Yes, It can be done with CSS, but defining this in HTML template has advantages:
- easy to do (inserting predefined classes from Bootstrap)
- readable code (Bootstrap classes are well known)

**Comment by bvaughn** [comment]
Sure, it's more flexible. I was just a bit reluctant to add another attribute to all directives. (Some of them are already quite large.)

I'm going to leave this issue open for now but I don't have the time to implement it. As you're the only person who's requested it so far, I'd be interested in accepting a pull request from you should you find the time to work on it. :)

**Comment by osimicek** [comment]
I have too many projects I am working on now. I will see if i find time to work on this. I would be glad if someone other adds a comment with his opinion or offer an implementation.

**Comment by bvaughn** [comment]
This is available in version [4.1.0](https://github.com/bvaughn/angular-form-for/releases/tag/4.1.0)

**Comment by osimicek** [comment]
That is awesome. Thanks!
