### ISSUE TITLE
text-field should support input filters

### ISSUE THREAD

**Issue by EnterpriseDT** [bvaughn/angular-form-for#151]
I'm seeing the error-message, `TypeError: this.$parse_(...).assign is not a function`.  It's coming from form-for.js.  Here's the full stack-trace:

    TypeError: this.$parse_(...).assign is not a function
        at NestedObjectHelper.writeAttribute (http://localhost/portal/lib/angular/js/form-for.js:843:37)
        at FormForStateHelper.setFieldHasBeenModified (http://localhost/portal/lib/angular/js/form-for.js:2718:38)
        at target.validateField (http://localhost/portal/lib/angular/js/form-for.js:1169:39)
        at Object.<anonymous> (http://localhost/portal/lib/angular/js/form-for.js:1072:28)
        at Object.scopePrototype.$watch.arguments.(anonymous function) [as fn] (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1905:36)
        at h.$get.h.$digest (http://localhost/portal/lib/angular/js/angular.min.js:110:373)
        at h.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1924:23)
        at h.$get.h.$apply (http://localhost/portal/lib/angular/js/angular.min.js:113:362)
        at h.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1987:22)
        at m (http://localhost/portal/lib/angular/js/angular.min.js:72:454)

I'm guessing I've got the wrong version of one of the includes or something, but I haven't managed to track it down yet.  Do you have any ideas?

Thanks
Hans

**Comment by bvaughn** [comment]
Sorry to hear that you're seeing an error. Can you provide a Plunker so I
can take a look?

$parse is a built-in Angular service so I'm not sure that a dependency is
to blame. Which versions of form for and Angular are you using?

**Comment by EnterpriseDT** [comment]
I was about to try to isolate the error when I noticed that it's occurring for fields that have filters.  Here's an example:

    <text-field label="Discount" attribute="payment.discount | currency:'$'" disable="true"></text-field>

I guess filters are not supported in attributes?

**Comment by bvaughn** [comment]
Oooh, no. Attributes are supposed to be the field name (e.g. username) or field path (e.g. user.firstName) within the form data object.

What are you trying to accomplish with the above filter? Is it just a display thing (prefixing the input value with "$" but not writing that value to the form-data object?)

**Comment by EnterpriseDT** [comment]
Oops.  Yes, it's just for formatting.  It formats it OK, but I see now that
parsing doesn't work, which is understandable.  How should I be doing this?

On 5 August 2015 at 11:30, Brian Vaughn <notifications@github.com> wrote:

> Oooh, no. Attributes are supposed to be the field name (e.g. username) or
> field path (e.g. user.firstName) within the form data object.
>
> What are you trying to accomplish with the above filter? Is it just a
> display thing (prefixing the input value with "$" but not writing that
> value to the form-data object?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bvaughn/angular-form-for/issues/151#issuecomment-127813031>
> .
>



-- 
Regards
Hans Andersen
EnterpriseDT

**Comment by bvaughn** [comment]
Hm, short answer is that there's no way to do this in formFor currently. Custom labels are easy but masking an input value is a request I haven't received before.

I'm open to the idea but I don't really have much spare time to build it myself. Any chance you may be interested in contributing some code? I'd be happy to review it :)

**Comment by EnterpriseDT** [comment]
I apologize for my noobishness, but could you please explain the phrases
'custom labels' and 'masking an input value'.  Neither or these mean
anything specific to me in the context of Angular.

On 6 August 2015 at 12:42, Brian Vaughn <notifications@github.com> wrote:

> Hm, short answer is that there's no way to do this in formFor currently.
> Custom labels are easy but masking an input value is a request I haven't
> received before.
>
> I'm open to the idea but I don't really have much spare time to build it
> myself. Any chance you may be interested in contributing some code? I'd be
> happy to review it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bvaughn/angular-form-for/issues/151#issuecomment-128219311>
> .
>



-- 
Regards
Hans Andersen
EnterpriseDT

**Comment by bvaughn** [comment]
No problem. It's not noobish. It's been a long day and my terminology is probably not good.

formFor supports configurable labels, by which I mean...you can choose the text (if any) that appears bolded before the input field. You can do this like so:

```html
<text-field label="My Custom Label">
```

Angular also has the concept of filters that format values coming from the model before they're displayed in the view. This is what you were trying to use. Unfortunately formFor doesn't support theres- or rather, it doesn't unless you create your own [custom input type](http://bvaughn.github.io/angular-form-for/#/demo/input-types).

**Comment by EnterpriseDT** [comment]
I just looked into it a bit more and saw that it's not even inherently
supported by Angular.  There's so much magic in Angular that I'd just
assumed/hoped that defining a filter in an ng-model (or form-for attribute)
field would link up both a formatter and a parser.  It appears that a
filter is only for formatting, which is perfectly understandable.

Actually, it's really not necessary for my input fields to be formatted as
currency, so I'll just present them as plain numbers.  It's a very minor
detail in the overall scheme of things, so it would be silly of me to
pursue it.

Thanks for your time once again.

**Comment by bvaughn** [comment]
Not a problem! Thanks for being so easy to chat with. :)

Going to close this issue for now then. If you change your mind about its importance- let's reopen it and talk more.
