### ISSUE TITLE
No option to add multiple custom rules to the same field

### ISSUE THREAD

**Issue by lintu** [bvaughn/angular-form-for#154]

**Comment by bvaughn** [comment]
Hi @lintu,

A custom rule is a function and so can be flexible enough to check as many things as you want.

You can accomplish multiple, chained validations like so:

```javascript
var customValidationA = function(value) {
  // Check something and return a promise
};

var customValidationB = function(value) {
  // Check something else and return a promise
};

var validationRules = {
  email: {
    required: true,
    custom: function(value) {
      var promiseA = customValidationA(value);
      var promiseB = customValidationB(value);

      return $q.all([customValidationA, customValidationB]);
    }
  }
};
```

**Comment by bvaughn** [comment]
Closing this issue because I assume the above solution should be flexible enough to work for you. If not, please feel free to re-open it and consider submitting a pull request! :)

**Comment by lintu** [comment]
One issue i am facing is I am not able to change the validation messages for different rules in "custom". Currently I am doing something like this

    if (conditionA) {
      _self.form.validationRules["fieldName"].custom.message = "message a";
      return false;
    }
    if (conditionB) {
      _self.form.validationRules["fieldName"].custom.message = "message B";
      return false;
    }

It is returning faster than applying the changes. Validation is showing the previous error message, not the currently set message. I may need to do a $scope.$apply() after changing the message. But it have other issues.

If you confirm, I will send a pull request.

**Comment by bvaughn** [comment]
Sorry for the slow response time @lintu. This was a very busy week and work and I didn't have time in the evenings to check Github.

You can change the validation message by throwing an error instead of returning `false`, like so:

```javascript
if (conditionA) {
  throw Error('Message A');
} else if (conditionB) {
  throw Error('Message B');
}
```
