### ISSUE TITLE
Problem with latest release

### ISSUE THREAD

**Issue by sgrady** [bvaughn/angular-form-for#162]
Use of text fields produces the below error -- rolled back to 4.1.2 -- seems fine. Something has been introduced subsequently. 

Error: [$compile:nonassign] Expression 'undefined' used with directive 'textField' is non-assignable!
http://errors.angularjs.org/1.3.19/$compile/nonassign?p0=undefined&p1=textField

**Comment by bvaughn** [comment]
@indrimuska Any ideas? Maybe related to PR #160 ?

**Comment by indrimuska** [comment]
I'm trying to find this issue, but I can reproduce the problem.
I also created this simple [Plunker](http://plnkr.co/edit/XAQvtSXfDjLcQcvUpQ68?p=preview), but it seems there's no errors.

Maybe this issue can be resolved by making the binding to the `controller` attribute optional.

@sgrady could you please provide a working example showing this trouble?

**Comment by bvaughn** [comment]
Ah. Right. Have you tried marking `controller: '=?'` @indrimuska ?

**Comment by sgrady** [comment]
Workin on an example

**Comment by sgrady** [comment]
In the textField directive, marking controller: '=?' fixes the problem. Good guess.

**Comment by bvaughn** [comment]
I'll make a quick fix release. Give me 5.

**Comment by bvaughn** [comment]
Check out release 4.1.5 and let me know if this resolves the issue for you @sgrady

**Comment by sgrady** [comment]
On 4.1.5. We are a go.

**Comment by bvaughn** [comment]
Glad to hear it. Thank you for your help reporting and verifying the fix :)
