### ISSUE TITLE
checkboxField change event does not fire

### ISSUE THREAD

**Issue by SyntaxUnknown** [bvaughn/angular-form-for#169]
Hello!

The 'changed' event in the checkboxField does not work because it's declared in the scope as an '@?' when it should be '&?'. Here's the error you get if you try to use it passing a function:

AngularJS error: fnPtr is not a function

Changing the scope declaration to '&?' corrects the issue and the event function gets called.

Thanks!!!

**Comment by bvaughn** [comment]
Thanks for filing this, @SyntaxUnknown. I'll get a patch release out for you in a few moments.
