### ISSUE TITLE
increment validation

### ISSUE THREAD

**Issue by hutzelknecht** [bvaughn/angular-form-for#170]
Hi Brian, thanks for the min/max/increment addition to textFields - works fine for me this way.

What exactly are you trying to validate in the ModelValidator in the method: validateFieldIncrement_()?
If it is the amount of decimal digits, it's propably better to use a RegEx like here: http://stackoverflow.com/questions/10454518/javascript-how-to-retrieve-the-number-of-decimals-of-a-string-number instead of a Modulo check, so that we would actually be counting the decimal digit length. The reason for this is that the following examples are all greater than zero and the validation failure message will always appear:

    10.1 % 0.1 // 0.09999999999999909
    10.11 % 0.1 // 0.009999999999998871
    10.99999999 % 0.1 // 0.09999998999999857

Am i misunderstanding the intention of the validation, or is this something that needs to be fixed?

**Comment by hutzelknecht** [comment]
Also see this link: http://stackoverflow.com/questions/3966484/floating-point-numbers-and-javascript-modulus-operator.
Following those solutions, the line would need to look like this:

    let normalize = 1/increment;
    (numericValue * normalize) % (increment * normalize) > 0

**Comment by bvaughn** [comment]
I'm glad it works for you. :)

I'm not trying to validate the number of decimal places, no. Just the increment/interval (I'm not sure the right word). Let's say your field was only valid if it had even numbers. You could use `interval=2` for this. That's what it's validating.

I agree that it's sort of a weird validation, but... I wasn't sure of a solution that was both in the spirit of formFor (describing data via its validation) and also supported your desire to use `<input type=number step=...>`

That being said, I agree that an `interval` less than one produces undesirable results. Hm. Not sure what to do with that.

**Comment by bvaughn** [comment]
PS. Just saw your second comment after replying to the first. (Sorry just woke up here.) That looks like it would solve the issue, yup :)

**Comment by bvaughn** [comment]
Thanks so much fro pointing this out. Sorry it took me several days to get to it but it will be resolved in the upcoming release.
