### ISSUE TITLE
SelectField auto selects the last option initially

### ISSUE THREAD

**Issue by hutzelknecht** [bvaughn/angular-form-for#181]
Hi Brian,

here's something that is giving me some headache: The SelectField initially selects the last option. Here is an example: https://jsfiddle.net/hutzelknecht/p18ssbgq/
I have debugged a little into formFor and cannot find anywhere in the code where the value is selected explicitly. Somewhere in updateEmptyOption though, the options get thrrown together with the emptyOption (or not if allowBlank is true). This time i am really clueless as to why this is happening.
Any ideas?

**Comment by bvaughn** [comment]
Hi Micha,

Unfortunately I don't have any ideas why this is happening. The interaction between formFor and select menus is probably the most complex/fragile/brittle part of the form library to be honest.

I don't have the bandwidth to dive into this right now. Maybe @indrimuska might be interested? Or if you'd be interested in submitting a PR yourself I'd be happy to review it. If it's blocking on me though it won't be done any time soon unfortunately.

**Comment by indrimuska** [comment]
Hi guys, I will take a look into this.
@hutzelknecht I've just seen the fiddle you posted, and I create this [plunker](http://plnkr.co/edit/0pBDSKzrF5vRtKnr2fly?p=preview) just to verify that you use the latest version of formfor.

The first thing I see is that you set your variable `this.data.name` to the string value `"1"`, but your options use integer values (`1`, `2`, ...).
```javascript
this.data = { name: '1' };
this.options = [
  { value: 1, label: 'Berta' },
  { value: 2, label: 'Caesar' },
  { value: 3, label: 'Donald' }
];
```
I don't know if you want to set your variable to the value `1`, if so you just need to remove the quotes.
```javascript
this.data = { name: 1 };
```

**Comment by bvaughn** [comment]
Ah, good call! I tried naming the `value` attributes strings in his original fiddle and that didn't resolve the issue. But in your updated one, it does.

**Comment by indrimuska** [comment]
Oh I haven't try that before. Maybe it could be cause by something that doesn't work with ui.bootstrap + formFor together, but in this [updated plunker](http://plnkr.co/edit/1DSJP6rbCZOXzHsAiiKA?p=preview) I can't see anything wrong.

**Comment by hutzelknecht** [comment]
I must have been using a really old version of *form-for.bootstrap-templates.js*.
https://jsfiddle.net/hutzelknecht/p18ssbgq/9/ (old file)
https://jsfiddle.net/hutzelknecht/p18ssbgq/10/ (using new file)
somehow it must have remained in my bower_components folder for a really long time even after calling ```bower install``` or it got in there in some other way i don't know. The version i have been using had a state of before July 12th, because back then instead of using ng-options, the options tags were created using  ng-repeat.
Thanks @indrimuska and @bvaughn for opening a new plunkr - that was the hint i needed.

**Comment by bvaughn** [comment]
Happy to hear you've got it ironed out. :)
