### ISSUE TITLE
JSON Schema support

### ISSUE THREAD

**Issue by elyas-bhy** [bvaughn/angular-form-for#184]
Any plans on making `angular-form-for` compatible with [JSON-Schema](http://json-schema.org/documentation.html) spec?

**Comment by bvaughn** [comment]
Unfortunately no, I have no plans of supporting this. JSON schema is very complicated and supporting it in a significant way would require a lot of work.

If you're looking for an Angular form abstraction that supports JSON schema I suggest you check out something like [Textalk/angular-schema-form](https://github.com/Textalk/angular-schema-form).
