### ISSUE TITLE
TypeError: Cannot read property 'unwatchers' of undefined

### ISSUE THREAD

**Issue by baconcutter** [bvaughn/angular-form-for#186]
Sometimes when my Angular app is starting, the error "TypeError: Cannot read property 'unwatchers' of undefined" occurs at the following method:

`
target.unregisterFormField = function (fieldName) {
	var bindableFieldName = nestedObjectHelper.flattenAttribute(fieldName);
	angular.forEach($scope.fields[bindableFieldName].unwatchers, function (unwatch) {
		unwatch();
	});
	delete $scope.fields[bindableFieldName];
};
`
I am using version 4.1.8 of angular-form-for.

**Comment by bvaughn** [comment]
Hi @baconcutter,

Sorry to hear about this issue you're experiencing. I'm not actively maintaining this library anymore though as the main README states. I have not been using Angular for some time and it's difficult and time consuming to switch contexts back and try to support newer releases of the library.

If you'd like to put together a PR for this issue I'd be happy to merge it and build a release though!

**Comment by bvaughn** [comment]
[Version 4.1.11](https://github.com/bvaughn/angular-form-for/blob/master/CHANGELOG.md#4111) has been released with your fix. Thank you for contributing!

**Comment by baconcutter** [comment]
Hi Brian,

Thank you for merging and releasing so quickly!

2016-03-08 3:11 GMT+01:00 Brian Vaughn <notifications@github.com>:

**Comment by bvaughn** [comment]
I try to keep things flowing smoothly :) especially when someone goes to
the effort of contributing.
