### ISSUE TITLE
Submit form with button which is outside form

### ISSUE THREAD

**Issue by palodelincak** [bvaughn/angular-form-for#46]
Is there some way how to submit form with button which is outside form? 

General example:

```
<div class='wrapper'>
   <form></form>
   <button ng-click='submit()'>Save form above</button>     
</div>
```

I especially need to trigger validation and show validation messages. I saw your implementation of manual validation, but it doesn't show validation messages.

**Comment by marthinal** [comment]
You can use html5 form attribute. Hope it helps :)

I.E. <button id="reportbuttonfound" class="button button-assertive" type="submit" form="foundform">

outside your form with id foundform.
