### ISSUE TITLE
model.required

### ISSUE THREAD

**Issue by mcheever** [bvaughn/angular-form-for#67]
Trying to get the requiredLabel to show up that depends on the required attribute in the fieldLabel directive.  Looking at the directive it is bound to model.required.  In form-for.js i can find where model.uid/model.error/model.bindable are set but not model.required.  Am i missing something?  i have a rule for the property require: true so would have expected the required label to show.

<field-label ng-if="label"
                 input-uid="{{model.uid}}"
                 iud="{{model.uid}}-label"
                 label="{{label}}"
                 required="{{model.required}}"
                 class="{{labelclasses}}">
    </field-label>

**Comment by bvaughn** [comment]
Hi @mcheever,

I hope you don't mind my reaching out to you in this way, but I have a small request I'd like to make of you. (And there will be no hard feelings if you don't have the time!)

I've recently started created a new JavaScript library named Task Runner (github.com/bvaughn/task-runner). If you're willing and able to take a few moments to look over the library, I'd love to hear your feedback. It's in the early stages (only 1 release) so there's still a lot of room for changes.

I think the library has a lot of potential, but before I push it out via Reddit and other forums, I'd love to get some unbiased feedback.

Cheers,
Brian

**Comment by mcheever** [comment]
Sure thing i will take a peek and see what it looks like!

Mike

**Comment by bvaughn** [comment]
I certainly appreciate it :)
