### ISSUE TITLE
masked input 

### ISSUE THREAD

**Issue by kevinspacey** [bvaughn/angular-form-for#77]
I think I'm getting annoying =)  how about adding an opportunity to mask input?

**Comment by bvaughn** [comment]
Hi @kevinspacey,

I hope you don't mind my reaching out to you in this way, but I have a small request I'd like to make of you. (And there will be no hard feelings if you don't have the time!)

I've recently started created a new JavaScript library named Task Runner (github.com/bvaughn/task-runner). If you're willing and able to take a few moments to look over the library, I'd love to hear your feedback. It's in the early stages (only 1 release) so there's still a lot of room for changes.

I think the library has a lot of potential, but before I push it out via Reddit and other forums, I'd love to get some unbiased feedback.

Cheers,
Brian

**Comment by kevinspacey** [comment]
Hi @bvaughn,
thanks for proposal, i'll try Task Runner and let you know
