### ISSUE TITLE
Problems with Select drop-down indicator icons, Chrome and Firefox

### ISSUE THREAD

**Issue by kokujin** [bvaughn/angular-form-for#79]
On Chrome. The opposing triangle icons on my selects are missing, everything else works, all the other widgets look fine. Does the form-for CSS have problems with the normal Zurb foundation CSS? Thanks
UPDATE: Its messed up in Firefox too, the triangles are visible but misaligned

**Comment by bvaughn** [comment]
Hi @kokujin,

I hope you don't mind my reaching out to you in this way, but I have a small request I'd like to make of you. (And there will be no hard feelings if you don't have the time!)

I've recently started created a new JavaScript library named Task Runner (github.com/bvaughn/task-runner). If you're willing and able to take a few moments to look over the library, I'd love to hear your feedback. It's in the early stages (only 1 release) so there's still a lot of room for changes.

I think the library has a lot of potential, but before I push it out via Reddit and other forums, I'd love to get some unbiased feedback.

Cheers,
Brian

**Comment by kokujin** [comment]
Hi Brian, sorry for taking so long, it had completely escaped my mind. I'll
try to take a look this week

Brian Vaughn <notifications@github.com> schrieb am Sa., 14. Feb. 2015 07:01:

**Comment by bvaughn** [comment]
No problem. I'm glad to hear that you're hopefully feeling better.
