### ISSUE TITLE
select-field : automatically select first available option 

### ISSUE THREAD

**Issue by pierre-michalet** [bvaughn/angular-form-for#82]
Hey,

I use filtered select fields and I was wondering if there is a way to select the first option on blur ?

Basically what I want to achieve is that a user can enter data in te field and press the tab key to switch to the next field without having to click on the option 

It will also help end to end testing with Protractor, because I have to simulate a click on the first available option for each select field

Thanks

**Comment by pierre-michalet** [comment]
Hello,

I don't need this anymore as we found another way to automate select field with protractor

Thanks !

**Comment by bvaughn** [comment]
Ok. Thanks for the update :)
