### ISSUE TITLE
feature request: validating number precision

### ISSUE THREAD

**Issue by walter4dev** [bvaughn/angular-form-for#85]
This is not an issue but a feature request. I was wondering if anyone has created a validation for number precision. Check out http://blog.yodersolutions.com/validate-and-format-numbers-in-angularjs/. Incorporating that level of validation into formfor would be great!

If I get time I'll see what I can do....

**Comment by bvaughn** [comment]
FYI this issue has been resolved in the new `type-script` branch and will be released once I've completed regression testing the newly rewritten formFor. :)

I didn't add the full set of features as defined by the plugin you referenced, but I did add `minimum` and `maximum` range support.

**Comment by bvaughn** [comment]
Just released 2.0.0 which contains this fix.
