### ISSUE TITLE
Feature request: customize textarea

### ISSUE THREAD

**Issue by taxp** [bvaughn/angular-form-for#87]
Hello!

It would be nice to have possibility to set standard attributes to textarea like rows, cols. Currently we have no means to fit its look to site layout

**Comment by bvaughn** [comment]
The text field directive already supports a `rows` attribute, but your request still makes sense. :)

formFor's templates were designed with that kind of flexibility in mind. You can accomplish it by overriding a single, small template: *form-for/templates/text-field/_textarea*

If you use the Bootstrap templates, you can fork this:
https://github.com/bvaughn/angular-form-for/blob/master/templates/bootstrap/text-field/_textarea.html

If you use formFor's custom templates, you can fork this:
https://github.com/bvaughn/angular-form-for/blob/master/templates/default/text-field/_textarea.html

The [text-field](https://github.com/bvaughn/angular-form-for/blob/master/source/directives/text-field.js) directive exposes a `$scope.attributes` property to the view that contains all of the HTML attributes you specified on the text field. So for instance, if your view was like this:

```html
<text-field label="Comments" attribute="comments" multiline rows="4" cols="40"></text-field>
```

Then your override of the `_textarea.html` template could access it like this:

```html
<textarea aria-manager
          id="{{model.uid}}"
          tabindex="{{tabIndex}}"
          ng-attr-placeholder="{{placeholder}}"
          rows="{{rows}}"
          cols="{{attributes.cols}}"
          ng-model="model.bindable"
          ng-disabled="disable || model.disabled"
          form-for-debounce="{{debounce}}"
          ng-click="onFocus()"
          ng-blur="onBlur()">
</textarea>
```

I *think* this should be enough to resolve our issue but if you run into any problems, I'd be happy to take a look. Just put up a Plunker and send me a link. :)

**Comment by bvaughn** [comment]
Hi @taxp,

I hope you don't mind my reaching out to you in this way, but I have a small request I'd like to make of you. (And there will be no hard feelings if you don't have the time!)

I've recently started created a new JavaScript library named Task Runner (github.com/bvaughn/task-runner). If you're willing and able to take a few moments to look over the library, I'd love to hear your feedback. It's in the early stages (only 1 release) so there's still a lot of room for changes.

I think the library has a lot of potential, but before I push it out via Reddit and other forums, I'd love to get some unbiased feedback.

Cheers,
Brian

**Comment by taxp** [comment]
Hi @bvaughn 
It is nice how your library allows to handle subtasks, conditionally execute some of them or another, with defined order. 
I also impressed that logical part of interaction of subtasks does not need tons of callback now.

I guess your lib would be useful to create js-app with clean logic, because usually logic gets complicated as size of code grows(millions of functions, callbacks and so one)

**Comment by bvaughn** [comment]
Thank you for the positive feedback @taxp. Much appreciated.

If you have any suggestions about ways to make Task Runner more appealing to developers like yourself- I'm all ears. :)
