### ISSUE TITLE
checkbox-field ng-click event

### ISSUE THREAD

**Issue by jmiazga** [bvaughn/angular-form-for#88]
Would it be possible to add a change event to the checkbox-field? I need to execute some code when a checkbox is toggled.

Thanks

**Comment by jmiazga** [comment]
created pull request to add this feature. #90

**Comment by bvaughn** [comment]
Much appreciated. Merged and will release with the next version.

**Comment by bvaughn** [comment]
Just wanted to let you know that this feature has been released with [version 1.7.0](https://github.com/bvaughn/angular-form-for/releases/tag/1.7.0).

**Comment by bvaughn** [comment]
Hi Jason,

I hope you don't mind my reaching out to you in this way, but I have a small request I'd like to make of you. (And there will be no hard feelings if you don't have the time!)

I've recently started created a new JavaScript library named Task Runner (github.com/bvaughn/task-runner). If you're willing and able to take a few moments to look over the library, I'd love to hear your feedback. It's in the early stages (only 1 release) so there's still a lot of room for changes.

I think the library has a lot of potential, but before I push it out via Reddit and other forums, I'd love to get some unbiased feedback.

Cheers,
Brian
