### ISSUE TITLE
feature request: allow field validations to appear if form isn't submitted and they haven't been modified

### ISSUE THREAD

**Issue by peterfairfield** [bvaughn/angular-form-for#91]
Use case; I want to import a bunch of data from somewhere and shove that data into a form, and I want to show the errors immediately, so the user doesn't have to guess what is wrong. Right now, I have to fake submit the form or fake modify the form fields to get the errors to appear. Essentially this would be adding some directive config param to:

```javascript
 if (hasFormBeenSubmitted || $scope.formForStateHelper.hasFieldBeenModified(bindableFieldName))
```

Before I write this, what do you think?

**Comment by bvaughn** [comment]
Whoa! Peter! How's it going? :)

There's almost an easier approach to what your'e trying to do, using the form `controller`. Essentially...

```html
<form form-for="formData" controller="formController">
```
```js
$scope.formController.validateForm()
```

The only problem with this is that, unless the fields are marked as dirty, validation errors won't be displayed.

Maybe I should accept a boolean parameter in that method that enables you to forcefully show failures? I could add that this weekend.

**Comment by peterfairfield** [comment]
Doing awesome dude! Yeah, I tried validateForm(), and was surprised when the validations didn't show up.

"The only problem with this is that, unless the fields are marked as dirty, validation errors won't be displayed."

Right, that's what 'feels hackish'. A boolean would be awesome. I can submit a PR, if you like.

**Comment by bvaughn** [comment]
Good! Glad to hear it! Tell everyone at RS I say hi. :)

Yeah, the intent of that function initially was just to expose validation problems to external code but...I didn't immediately see a use-case for displaying errors. Totally can now though.

Sure, feel free to submit a PR if you get to it before I do! Either way I'll try to get a release cut over the weekend. :)

**Comment by bvaughn** [comment]
Hey @peterfairfield. Sorry it took me a little longer to get around to this than I'd hoped, but last week was a wash. [Release 1.7.1](https://github.com/bvaughn/angular-form-for/releases/tag/1.7.1) is out now though, with this feature. The [`validateForm()` method](http://rawgit.com/bvaughn/angular-form-for/master/dist/docs/form-for.js.html#line358) accepts a `Boolean` parameter that allows you to show errors on failure.

Let me know if you run into any problems! I tested it with collections too and it seems solid.

**Comment by peterfairfield** [comment]
Thanks so much Brian! I meant to get on this sooner, too.

**Comment by bvaughn** [comment]
No problem man. Hope it meets your needs!

**Comment by bvaughn** [comment]
Peter, dude! I know you're busy these days, but I'd love to hear your thoughts on a new JS library I've been working on - https://github.com/bvaughn/task-runner

No worries if you're too busy, but if not... :)
