### ISSUE TITLE
select-field : empty placeholder

### ISSUE THREAD

**Issue by pierre-michalet** [bvaughn/angular-form-for#92]
Hey,

for my select inputs, I would prefer to have an empty option instead of the default 'Select' text.
I think it's not possible at this time, I tried to pass an empty string as the placeholder attribute and to remove completely this attribute but the default 'Select' keep showing.

Could you fix it please ?

Thanks

**Comment by bvaughn** [comment]
I suppose I could change the code to check if `$attributes.hasOwnProperty('placeholder')` but until I find time to make that change and release, you can work around this by passing in a space or something (`placeholder=" "`).

**Comment by bvaughn** [comment]
FYI this issue has been resolved in the new `type-script` branch and will be released once I've completed regression testing the newly rewritten formFor. :)

**Comment by bvaughn** [comment]
Just released 2.0.0 which contains this fix.
