### ISSUE TITLE
Bug in ModelValidator.validateField

### ISSUE THREAD

**Issue by cheeverm3** [bvaughn/angular-form-for#96]
When using the following rule where required.rule can be dynamically set

required: {
    rule: false,
   message: "incorrect"
}

the following code in validateField erroneously rejects 

if (rules.required) {
                        var required = angular.isObject(rules.required) ? rules.required.rule : rules.required;

                        if (!!value !== required) {
                            return $q.reject(
                              angular.isObject(rules.required) ?
                                rules.required.message :
                                FormForConfiguration.validationFailedForRequiredMessage);
                        }
                    }

So if value = "password1" the if statement  if (!!value !== required)  converts to if(true !== false) which fails.  The problem is that code should never run (required.rule == false)...however because i am using an object instead of a primitive value if (rules.required) will always evaluate to true.  A possible solution would be 

var required = angular.isObject(rules.required) ? rules.required.rule : rules.required;
if (required) {
                if (!!value !== required) {
                            return $q.reject(
                              angular.isObject(rules.required) ?
                                rules.required.message :
                                FormForConfiguration.validationFailedForRequiredMessage);
                        }
                    }

This seems to be the only one that has a problem since the value is truthy.

**Comment by bvaughn** [comment]
Thanks for the bug report. I apologize that you had to find this the hard way. :)

I'm out of town for the morning but I'll try to fix this in the evening and make a release. I'll notify you once it's available.

**Comment by bvaughn** [comment]
Fixed and released as `1.7.2`. Thanks so much for reporting this issue! :)

By the way, if you have a few moments I'd love to get your input on another JavaScript project I've recently started. It's on Github also: https://github.com/bvaughn/task-runner

Cheers!
