### ISSUE TITLE
validation error count

### ISSUE THREAD

**Issue by kevinspacey** [bvaughn/angular-form-for#97]
Hello, @bvaughn
After form validation failed, How i can get error count or maybe object with failed attributes?

**Comment by bvaughn** [comment]
Error count?

If you're using form for's `controller.validateForm()` method the Promise rejection handler will be provided an object containing all of the fields/attributes that failed validation.

The same is true if you provide a `<form form-for submit-error="submitError(error)">` function. Your `submitError` method will be passed an object that contains attributes for each of the failed fields.

**Comment by kevinspacey** [comment]
It's what i need, thanks!

**Comment by bvaughn** [comment]
Glad to hear it! :)
