### ISSUE TITLE
i18n support ?

### ISSUE THREAD

**Issue by mydearxym** [bvaughn/angular-form-for#98]
amazing work!
but how can i `i18n` the  "Required field" staff with other lang ?

**Comment by bvaughn** [comment]
Thank you!

Couple of options:
1) Use the [FormForConfiguration.setRequiredLabel() method](http://rawgit.com/bvaughn/angular-form-for/master/dist/docs/form-for-configuration.js.html#line100). This is the easiest route, but will only work if you are able to set the value before your form(s) are shown. (Forms that are already showing will not be dynamically updated.)
2) Fork the (very small) `field-label` template (for [bootstrap](https://github.com/bvaughn/angular-form-for/blob/master/templates/bootstrap/field-label.html) or [default](https://github.com/bvaughn/angular-form-for/blob/master/templates/default/field-label.html) skin). This is a little more work, but will give you the ability to add in an i18n binding.

If either of the above options are too much work/hassle, let me know and I can find time to add in a more proper support for this sometime over the next few days. :)

PS. If you've been enjoying formFor, and have a few moments to spare, I'd love to hear your thoughts on a new framework I'm working on called [Task Runner](http://bvaughn.github.io/task-runner/). Just trying to raise awareness in general. :)

**Comment by bvaughn** [comment]
Hi again @mydearxym,

Since I haven't heard back from you I'm going to assume that one of the above suggestions worked. Please let me know if not and we can re-open this issue.
